# Generated by Django 5.0.7 on 2024-08-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
