# Generated by Django 5.1 on 2024-09-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
